[project]
name = "datagouv-ai-evaluation"
version = "0.1.0"
description = "Utils to evaluate Data Gouv's implementation of AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opik>=1.0.0",
    "asyncio>=4.0.0",
    "mcp>=1.26.0",
    "numpy>=2.4.2",
    "openai>=2.24.0",
    "openinference-instrumentation-mcp>=1.3.3",
    "openinference-instrumentation-openai>=0.1.41",
    "openinference-instrumentation-pydantic-ai>=0.1.12",
    "opentelemetry-api>=1.40.0",
    "opentelemetry-exporter-otlp>=1.40.0",
    "opentelemetry-sdk>=1.40.0",
    "pydantic-ai>=0.8.1",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pandas>=3.0.1",
]

[dependency-groups]
dev = ["black>=26.1.0", "ruff>=0.15.4"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
