# ─────────────────────────────────────────────
# TASK 03
# ─────────────────────────────────────────────

task_id: task_0003
task_name: Objets mobiliers classés monuments historiques

meta:
  status: active
  source: support

prompt: >
  Je débute l'inventaire d'une cathédrale, Cathédrale Saint-Jean de Belley.
  Où trouver les fiches des objets qui pourraient être classés monuments historiques ?


evaluation_criteria:
  minimal:
    - criteria: >
        Agent returns the dataset "Liste des objets protégés au titre des Monuments historiques".
    - criteria: >
        Agent does not confuse between the protected objects/furniture dataset and the buildings one.
    - criteria: >
        Agent provides a direct link or clear path for the user to access or download the relevant resource.


  optimal:
    - criteria: >
        Agent explains how to filter the dataset using columns like "Département" or "Département format numérique",
        "Commune forme index", "Nom de l'édifice" to find Cathédrale Saint-Jean de Belley.
    - criteria: >
        Agent notes that the CSV is not available via the tabular API so it cannot be queried by the agent.
    - criteria: >
        Agent notes that the CSV is over 300 Mo which could slow a bit the RAM to open it fully with a spreadsheet software.
    - criteria: >
        Agent notes that the CSV has been updated recently, like announced in the description (every Friday).


action_chain:
  minimal:
    chain: search.datasets > get.dataset.info
    required_actions:
      - name: search.datasets
        args:
          - name: query
            criteria: >
              Semantically relevant to classified or protected historic objects.
              e.g. "objets mobiliers monuments historiques", "mobilier classé MH"
      - name: get.dataset.info
        args:
          - name: dataset_id
            strict_value: "615bcdd729be9185b3b0681a"  # active dataset

  optimal:
    chain: search.datasets > get.dataset.info > get.dataset.resources > get.resource.info
    required_actions:
      - name: get.dataset.resources
        args:
          - name: dataset_id
            strict_value: "615bcdd729be9185b3b0681a"
      - name: get.resource.info
        args:
          - name: resource_id
            criteria: Resource ID of the main CSV file in the dataset


resources:
  - type: dataset
    id: "615bcdd729be9185b3b0681a"  # active dataset
    checks:
      - fn: same_title_description
        params: {id: ~}
  - type: resource
    dataset_id: "615bcdd729be9185b3b0681a"
    id: "3e8ed2dd-4052-4f93-ad19-ef71016ab7b4"  # palissy.csv, 344MB — updated every Friday
    checks:
      - fn: same_title_description
        params: {id: ~}
      - fn: update_date_more_recent_than
        params: {type: relative, value: last_7_days}
      - fn: download_url_reachable
        params: {}
