# ─────────────────────────────────────────────
# TASK 08
# ─────────────────────────────────────────────

task_id: task_0008
task_name: Shapefiles petites régions agricoles Hauts-de-France (Picardie)

meta:
  status: active
  source: forum

prompt: >
  Je suis à la recherche des données Shapefile des petites régions agricoles des
  Hauts de France. J'ai le Nord Pas de Calais, mais impossible de trouver la Picardie.


evaluation_criteria:
  minimal:
    - criteria: >
        Agent finds "Petites régions agricoles Hauts-de-France".

    - criteria: >
        Agent points to the zip resource which covers for
        the full Hauts-de-France region.

    - criteria: >
        Agent points out that it is unsure whether the zip contain shapefiles
        but it might as the tags speaks about "zonage" and "referential".

    - criteria: >
        Agent provides the download URL or clear path to access the resource.

    - criteria: >
        Agent does not provide unrelated PRA datasets from other regions.

  optimal:
    - criteria: >
        Agent clarifies that since the 2016 regional merger, Hauts-de-France
        covers both former Nord-Pas-de-Calais and Picardie, so the zip from "Petites régions agricoles Hauts-de-France"
        should contain both territories - unlike "Limites administratives à grande échelle des petites régions agricoles Nord - Pas-de-Calais".

    - criteria: >
        Agent notes that the dataset description is sparse and recommends
        the user verify the shapefile content after download.


action_chain:
  minimal:
    chain: search.datasets > get.dataset.info > get.dataset.resources
    required_actions:
      - name: search.datasets
        args:
          - name: query
            criteria: >
              Semantically relevant to agricultural small regions in Picardie.
              e.g. "régions agricoles Picardie", "PRA Picardie"
      - name: search.datasets
        args:
          - name: query
            criteria: >
              Semantically relevant to agricultural small regions in Hauts-de-France.
              e.g. "petites régions agricoles Hauts-de-France", "PRA Hauts-de-France",
      - name: get.dataset.info
        args:
          - name: dataset_id
            strict_value: "69f29c59706271dc9a2c49ba"
      - name: get.dataset.resources
        args:
          - name: dataset_id
            strict_value: "69f29c59706271dc9a2c49ba"
      - name: get.resource.info
        args:
          - name: resource_id
            strict_value: "418ae28c-71e5-41ca-95c0-a77fd7d21d1f"

resources:
  - type: dataset
    id: "69f29c59706271dc9a2c49ba"  # Petites régions agricoles Hauts-de-France
    checks:
      - fn: same_title_description
        params: {id: ~}
