# action.object_type(s).object_facet.by_category
#

vocabulary:

  actions:
    - search: search/find by semantic/keyword query
    - get: get/list
    - analyze: filters/computation to return specific data (aggregate, exact value, ...)
  object_types:
    - dataset : dataset object
    - resource : resource tied to a dataset
    - data : data content of a resource
    - dataservice : third-party API
    - organization : organization
  object_facet: # can be different based on object_type
    - resources # for dataset only
    - update_date 
    - create_date
    # - more

semantic_layer:

  - actions:

    - search.datasets :
      description : |
        search dataset candidates based on a query and/or filters
      mcp : 
        - version: "<=0.2.24"
          tools: ["search_datasets"]
      cli :
        - version: ""
          commands: [""]
      api : 
        - domain: "https://www.data.gouv.fr/api/1"
          version: "==1"
          endpoints: ["GET /datasets/?q={query}"]

    - search.dataservices :
      description : |
        search dataservices candidates based on a query and/or filters
      mcp : 
        - version: "<=0.2.24"
          tools: ["search_dataservices"]
      cli :
        - version: ""
          commands: [""]
      api : 
        - domain: "https://www.data.gouv.fr/api/1"
          version: "==1"
          endpoints: ["GET /dataservices/?q={query}"]

    - get.dataset.info :
      description : |
        get info of a dataset based on dataset_id
      mcp : 
        - version: "<=0.2.24"
          tools: ["list_resources"]
      cli :
        - version: ""
          commands: [""]
      api : 
        - domain: "https://www.data.gouv.fr/api/1"
          version: "==1"
          endpoints: ["GET /datasets/{id}/resources/"]

    - get.resource.profile :
      description : |
        get a resource data profile (schema,  cols, etc)
      mcp : 
        - version: "<=0.2.24"
          tools: ["list_resources"]
      cli :
        - version: ""
          commands: [""]
      api : 
        - domain: "https://tabular-api.data.gouv.fr/api"
          version: "==1"
          endpoints: ["GET /resources/{rid}/profile/"]

    - get.dataset.resources :
      description : |
        list the resources tied to a dataset based on dataset_id
      mcp : 
        - version: "<=0.2.24"
          tools: ["list_resources"]
      cli :
        - version: ""
          commands: [""]
      api :
        - domain: "https://www.data.gouv.fr/api/1"
          version: "==1"
          endpoints: ["GET /datasets/{id}/resources/"]

    - get.data : 
      description : | 
          get all data of a specific resource
      mcp :
        - version: "<=0.2.24"
          tools: ["query_resource_data"]
      cli :
        - version: ""
          commands: [""]
      api :
        - domain: "https://tabular-api.data.gouv.fr/api"
          version: "==1"
          endpoints: ["GET /resources/{rid}/data/"]

    - analyze.data : 
      description : | 
          query data of a specific resource applying filters/aggregate
      mcp :
        - version: "<=0.2.24"
          tools: ["query_resource_data"]
      cli :
        - version: ""
          commands: [""]
      api :
        - domain: "https://tabular-api.data.gouv.fr/api"
          version: "==1"
          endpoints: ["GET /resources/{rid}/data/"]
        - domain: "https://www.data.gouv.fr/api/1"
          version: "==1"
          endpoints: ["GET /datasets/r/{rid}"]
      

  - args_name_matching: # Consider than naming is consistent over a framework

      - dataset_id: 
        - mcp: 
          version : "<=0.2.24"
          name : "dataset_id"
        - api: 
          version : "==1"
          name : "id"
        - cli:
          version : "==1"
          name : "id"

      - resource_id:
        - mcp: 
          version : "<=0.2.24"
          name : "resource_id"
        - api: 
          version : "==1"
          name : "rid"
        - cli:
          version : "==1"
          name : "id"
          
      - query:
        - mcp: 
          version : "<=0.2.24"
          name : "query"
        - api: 
          version : "==1"
          name : "q"
        - cli:
          version : "==1"
          name : ""
    


